import React, { useState } from 'react';
import type { CustomerFilters } from '../../../api/customer';
import customerAPI from '../../../api/customer';

interface ExportButtonProps {
  filters: CustomerFilters;
}

export const ExportButton: React.FC<ExportButtonProps> = ({ filters }) => {
  const [isExporting, setIsExporting] = useState(false);
  const [exportFormat, setExportFormat] = useState<'csv' | 'pdf'>('csv');

  const handleExport = async () => {
    try {
      setIsExporting(true);
      
      // In a real implementation, you would call an export API
      // For now, we'll simulate the export
      
      const response = await customerAPI.getAllCustomers(filters);
      
      if (response.status) {
        // Convert to CSV
        if (exportFormat === 'csv') {
          const csvContent = convertToCSV(response.data);
          downloadCSV(csvContent, 'customers.csv');
        } else {
          // For PDF, you would typically call a backend endpoint
          alert('PDF export would be generated by the backend');
        }
      }
    } catch (error) {
      console.error('Export failed:', error);
      alert('Export failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const convertToCSV = (data: any[]) => {
    const headers = ['Customer Code', 'Name', 'Email', 'Phone', 'Type', 'Status', 'Balance', 'Last Purchase'];
    const rows = data.map(customer => [
      customer.customer_code,
      customer.display_name || `${customer.first_name} ${customer.last_name}`,
      customer.email || '',
      customer.phone || customer.mobile || '',
      customer.customer_type,
      customer.status,
      customer.current_balance,
      customer.last_purchase_at ? new Date(customer.last_purchase_at).toLocaleDateString() : '',
    ]);

    return [headers, ...rows].map(row => row.join(',')).join('\n');
  };

  const downloadCSV = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="relative">
      <button
        onClick={handleExport}
        disabled={isExporting}
        className="px-4 py-2 bg-green-600 hover:bg-green-700 disabled:opacity-50 text-white rounded-lg transition-colors flex items-center gap-2"
      >
        {isExporting ? (
          <>
            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
            Exporting...
          </>
        ) : (
          <>
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Export
          </>
        )}
      </button>

      <div className="absolute right-0 mt-2 w-48 bg-gray-800 border border-gray-700 rounded-lg shadow-lg z-10">
        <div className="p-2">
          <div className="text-sm text-gray-300 mb-2">Export Format:</div>
          <div className="flex gap-2">
            <button
              onClick={() => setExportFormat('csv')}
              className={`flex-1 px-3 py-2 rounded text-sm ${
                exportFormat === 'csv' 
                  ? 'bg-blue-600 text-white' 
                  : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
              }`}
            >
              CSV
            </button>
            <button
              onClick={() => setExportFormat('pdf')}
              className={`flex-1 px-3 py-2 rounded text-sm ${
                exportFormat === 'pdf' 
                  ? 'bg-blue-600 text-white' 
                  : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
              }`}
            >
              PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};